name: PR checks
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.15'
      - name: Build
        run: go build -o redeployster .
      - name: Format Check
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Go code is not properly formatted:"
            gofmt -d .
            exit 1
          fi